Python Essential: Numpy
    # Numpy is called Numerical Python.
    # Numpy is library for python programing.
    # It is widly used by Scientific community in Research and Development.
    # Orginal Author : Travis Oliphant in 2005 as community resarcher.
    # Numpy provides support for large , multi- dimentional array and matrices.
    # Numpy provides a high-performance Multi-dimensional arrary objects and tools for working with these objects.
    # It's one of the core library for Datascience projects.
    
    Short cuts:
    Shift+tab = tooltip
    Shift+Enter = Run Cell Select below
    Ctrl +Enter = Run Cell
    Alt+Enter  = Run cell, insert below
    
    

In [2]:
import numpy as np

In [5]:
# numpy with static array
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Array are homogenious,it do not have different datatypes
a.dtype
a = np.array([1,2,3,4,5.5,6,7,8,9])
a

array([1. , 2. , 3. , 4. , 5.5, 6. , 7. , 8. , 9. ])

In [12]:
# Array can be integer or float , its convert all the elements into float 1. , 2. ,...
a.dtype

dtype('float64')

In [13]:
# auto generate array with arange , its handy function sometime used generating sequence
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#ndim used to know how may dimention array is eg . below is single dimention
b =np.arange(20)
b.ndim

1

In [19]:
# Creating a 2 -dimention array with arange function
c = np.array([[2,4],[3,6],[4,6]])
c

array([[2, 4],
       [3, 6],
       [4, 6]])

In [22]:
# function output goes to reshape to two dimention
# reshape(5,6) 5 rows and 6 columns
d = np.arange(30).reshape(5,6)
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [23]:
# Shape function tell what is shape of array
d.shape

(5, 6)

In [24]:
# Checking dimention , its 2 dim array
d.ndim

2

In [25]:
# size of elements
d.size

30

In [27]:
# type(d) tells the what type variable is
type(d)

numpy.ndarray

In [30]:
# zeros function create 0
e = np.zeros((3,4))
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])